// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type OrderReply struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

type OrderReq struct {
	Id string `path:"id"`
}
